CREATE TABLE IF NOT EXISTS CUSTOMERS (
  ID         INT IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR,
  LAST_NAME  VARCHAR
);

CREATE TABLE IF NOT EXISTS ORDERS (
  ID          INT IDENTITY PRIMARY KEY,
  CUSTOMER_ID INT,
  DESCRIPTION VARCHAR
)
