CREATE SCHEMA TASKS
  AUTHORIZATION SA;

CREATE TABLE IF NOT EXISTS TASKS.USERS (
  ID    INT IDENTITY PRIMARY KEY,
  LOGIN VARCHAR NOT NULL,
  NAME  VARCHAR NOT NULL
);
ALTER TABLE TASKS.USERS ADD CONSTRAINT LOGIN_UNIQUE UNIQUE (LOGIN);

CREATE TABLE IF NOT EXISTS TASKS.LISTS (
  ID      INT IDENTITY PRIMARY KEY,
  SUMMARY VARCHAR
)
